### ISSUE TITLE
cue formatting does not work (windows env related?)

### ISSUE THREAD

**Issue by ncomet** [monogon-dev/intellij-cue#49]
Hi, 

First of all thanks a lot for this great plugin, and this awesome work.

Here is the issue I'm facing:

- Windows 10 Pro
- Goland IDE
- cue.exe is present in my PATH on windows.
- open a .cue file, everything is fine
- when trying to format with CTRL+ALT+L, it does't work, meaning no cue fmt is launched.

Am I missing something ?

Thank you !

**Comment by jansorg** [comment]
@ncomet Can you try to define the path to CUE at `Preferences > Languages & Frameworks > CUE Language`, please?

**Comment by ncomet** [comment]
@jansorg Thanks a lot, that was indeed the issue. I'm closing this !
