### ISSUE TITLE
Compatibility with new version of IntelliJ (2022.1)

### ISSUE THREAD

**Issue by darh** [monogon-dev/intellij-cue#51]
Can you maybe handle compatibility with new versions? 

If there is no maintainer for this, I can dig help.

**Comment by leoluk** [comment]
Should be working on the most recent versions. What's missing?

**Comment by darh** [comment]
Apologies, I was not clear: 

Plugin (0.8.3) is disabled with message:

> Incompatible: requires IDE build 213.** or earlier

**Comment by dave08** [comment]
It just came out as stable today... and this plugin is VERY important, it would be great to have an update, thanks!

**Comment by leoluk** [comment]
Will be updated ASAP

**Comment by marcellanz** [comment]
Thanks a lot. I'm already missing it :D

**Comment by leoluk** [comment]
Via https://github.com/monogon-dev/intellij-cue/pull/52, will be available after JetBrains approval.
