### ISSUE TITLE
Parse error for `(string): {}`

### ISSUE THREAD

**Issue by stefanprodan** [monogon-dev/intellij-cue#53]
Hello, first of all, thank you very much for this plugin 👍 

The parser fails to understand syntax like this:

```cue
command: test: {
	for t in tests {
		(t.name): {
			print: cli.Print & {
				text: "testing \(t.name)"
			}
		}
	}
}
```
<img width="470" alt="Screenshot 2022-04-18 at 12 02 15" src="https://user-images.githubusercontent.com/3797675/163785052-619cf5e9-85fa-4f87-af2a-1870e43d1bb3.png">

**Comment by myitcv** [comment]
Per an exchange with @jansorg on CUE slack, the missing piece in the puzzle here is an update in the CUE spec for dynamic fields: https://github.com/cue-lang/cue/issues/2267

**Comment by stefanprodan** [comment]
Thanks a lot @myitcv! I've updated the plugin and I can confirm this issue has been fixed.

**Comment by myitcv** [comment]
Wonderful, @stefanprodan! Thanks @jansorg for the fix.

**Comment by fionera** [comment]
This is still an issue as soon as you add another prefix
```
metadata: (k): v
```

**Comment by jansorg** [comment]
@fionera Thanks! I'd rather wait for the official grammar at https://github.com/cue-lang/cue/issues/2267 before I attempt again to guess what the grammar is supposed to be.

**Comment by jansorg** [comment]
Version 0.10.0 should fix this. It'll be available soon on the Marketplace.
