### ISSUE TITLE
New version of IntelliJ requires requires build 223.* or older of plugin

### ISSUE THREAD

**Issue by myitcv** [monogon-dev/intellij-cue#59]
A number of users are reporting that newer versions of IntelliJ are seeing the following message:

```
Plugin 'CUE' (version '0.8.5') is not compatible with the current version of the IDE, because it requires build 223.* or older but the current build is IU-231.4840.387 Plugin 'Kotest' (version
```

I don't use IntelliJ myself, so I'm creating this issue as more of a placeholder for discussion and for others to comment with specifics.

**Comment by jansorg** [comment]
Thanks, a fix is underway.

**Comment by jansorg** [comment]
The update is now available, https://plugins.jetbrains.com/plugin/16126-cue/versions/stable/300843

**Comment by myitcv** [comment]
@jansorg thanks so much for this.
